In [1]:
from tensorflow.keras.preprocessing.text import one_hot



In [2]:
sent=['The glass of milk',
    'the glass of juice',
    'the cup of the tea',
    'i am a good reader',
    'i am a good gymnasium',
    'see you soon'
]

In [3]:
voc_size=10000

In [4]:
one_hot_repr=[one_hot(word,voc_size) for word in sent]
one_hot_repr

[[2329, 6273, 965, 3841],
 [2329, 6273, 965, 5067],
 [2329, 8247, 965, 2329, 7175],
 [2273, 7699, 8661, 8020, 1384],
 [2273, 7699, 8661, 8020, 9389],
 [2701, 3845, 6847]]

In [5]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import  pad_sequences
from tensorflow.keras.models import Sequential

In [6]:
import numpy as np

In [7]:
sent_length=8
embedded_doc=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
embedded_doc

array([[   0,    0,    0,    0, 2329, 6273,  965, 3841],
       [   0,    0,    0,    0, 2329, 6273,  965, 5067],
       [   0,    0,    0, 2329, 8247,  965, 2329, 7175],
       [   0,    0,    0, 2273, 7699, 8661, 8020, 1384],
       [   0,    0,    0, 2273, 7699, 8661, 8020, 9389],
       [   0,    0,    0,    0,    0, 2701, 3845, 6847]])

In [8]:
dim=10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
model.predict(embedded_doc)

1/1 [==============================] - 0s 345ms/step


array([[[ 0.01956588,  0.02911866, -0.03009321,  0.04264754,
         -0.0303699 ,  0.02592285,  0.02118723,  0.02983054,
         -0.03666165, -0.02450736],
        [ 0.01956588,  0.02911866, -0.03009321,  0.04264754,
         -0.0303699 ,  0.02592285,  0.02118723,  0.02983054,
         -0.03666165, -0.02450736],
        [ 0.01956588,  0.02911866, -0.03009321,  0.04264754,
         -0.0303699 ,  0.02592285,  0.02118723,  0.02983054,
         -0.03666165, -0.02450736],
        [ 0.01956588,  0.02911866, -0.03009321,  0.04264754,
         -0.0303699 ,  0.02592285,  0.02118723,  0.02983054,
         -0.03666165, -0.02450736],
        [-0.02444453, -0.04361647,  0.03489368, -0.03787602,
          0.02038454,  0.0130262 , -0.03918128, -0.03842449,
         -0.01018203,  0.02806393],
        [-0.04385542,  0.0342934 ,  0.01148901, -0.03484005,
          0.02494968, -0.02723792, -0.02264353, -0.02229619,
         -0.01604805, -0.00925022],
        [ 0.01920924, -0.0019199 ,  0.01747807,  0.0

In [13]:
embedded_doc[0]

array([   0,    0,    0,    0, 2329, 6273,  965, 3841])

In [14]:
model.predict(embedded_doc[0])

1/1 [==============================] - 0s 76ms/step


array([[ 0.01956588,  0.02911866, -0.03009321,  0.04264754, -0.0303699 ,
         0.02592285,  0.02118723,  0.02983054, -0.03666165, -0.02450736],
       [ 0.01956588,  0.02911866, -0.03009321,  0.04264754, -0.0303699 ,
         0.02592285,  0.02118723,  0.02983054, -0.03666165, -0.02450736],
       [ 0.01956588,  0.02911866, -0.03009321,  0.04264754, -0.0303699 ,
         0.02592285,  0.02118723,  0.02983054, -0.03666165, -0.02450736],
       [ 0.01956588,  0.02911866, -0.03009321,  0.04264754, -0.0303699 ,
         0.02592285,  0.02118723,  0.02983054, -0.03666165, -0.02450736],
       [-0.02444453, -0.04361647,  0.03489368, -0.03787602,  0.02038454,
         0.0130262 , -0.03918128, -0.03842449, -0.01018203,  0.02806393],
       [-0.04385542,  0.0342934 ,  0.01148901, -0.03484005,  0.02494968,
        -0.02723792, -0.02264353, -0.02229619, -0.01604805, -0.00925022],
       [ 0.01920924, -0.0019199 ,  0.01747807,  0.00480824, -0.0102108 ,
        -0.04851462,  0.01716531,  0.03048832